import { useEffect } from "react";
import Head from "next/head";
import Link from "next/link";
import { useProductStore } from "@/store/useProductStore";
import { useFetchData } from "@/hooks/useFetchData";
import { TProductsResponse } from "@/types";
import { Button } from "@/components/ui/button";
import { ProductList } from "@/components/products/ProductList";
import { ProductFilter } from "@/components/products/ProductFilter";
import { ProductPagination } from "@/components/products/ProductPagination";
import { Loader, SquarePlus } from "lucide-react";

export default function Home() {
  const { products, favorites, filter, pagination, setProducts, setPagination, getPaginatedProducts, clearFavorites } = useProductStore();
  const { data, loading, error, fetchData } = useFetchData<TProductsResponse>();

  useEffect(() => {
    if (products.length === 0) {
      clearFavorites();
      setPagination(1, pagination.limit, 0)

      fetchData(
        'https://cors-anywhere.herokuapp.com/https://dummyjson.com/products?limit=100',
        {
          headers: {
            "Origin": "https://dmiweb.github.io/products-app-next/"
            // "Origin": "http://localhost:3000/" 
          }
        });
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  useEffect(() => {
    if (data) {
      setProducts(data.products);
      setPagination(pagination.page, pagination.limit, data.products.length);
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [data]);

  const currentProducts = getPaginatedProducts();

  if (loading) {
    return (
      <div className='absolute left-2/4 top-1/3 transform -translate-x-1/2'>
        <Loader className='animate-spin' />
      </div>
    );
  }

  if (error) {
    return <div className='absolute left-2/4 top-1/3 transform -translate-x-1/2'>{error}</div>
  }

  return (
    <>
      <Head>
        <title>Product List Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="flex min-h-screen items-center justify-center bg-zinc-50">
        <main className="flex flex-col p-4 min-h-screen w-full max-w-6xl bg-white">
          <h1 className={"mb-4 text-center text-4xl text-zinc-800"}>
            Список продуктов
          </h1>

          <div className='flex justify-between px-4'>
            <Link href="/products/create">
              <Button variant="outline" className='text-lg text-zinc-800 font-normal cursor-pointer'>
                <SquarePlus />
                Добавить продукт
              </Button>
            </Link>

            <ProductFilter />
          </div>

          {products.length
            ? <ProductList
              products={currentProducts}
              favorites={favorites}
              filter={filter}
            />
            : null}

          {pagination.total > pagination.limit && (
            <div className='self-center mt-auto p-4'>
              {filter === "all" && <ProductPagination />}
            </div>
          )}
        </main>
      </div>
    </>
  );
}
