import { useEffect } from "react";
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import { Geist, Geist_Mono } from "next/font/google";
import { useProductStore } from "@/store/useProductStore";
import { useFetchData } from "@/hooks/useFetchData";
import { TProductsResponse } from "@/types";
import styles from "@/styles/Home.module.css";
import { ProductList } from "@/components/products/ProductList";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export default function Home() {
  const { products, favorites, filter, setProducts } = useProductStore();
  const { data, loading, error, fetchData } = useFetchData<TProductsResponse>();

  useEffect(() => {
    if (products.length === 0) {
      fetchData('https://jsonexamples.com/products?limit=100');
    }
  }, []);

  useEffect(() => {
    if (data) {
      setProducts(data.products);
    }
  }, [data]);

  if (loading) return <div>Loading...</div>;
  if (error) return <div>{error}</div>;

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div
        className={`${styles.page} ${geistSans.variable} ${geistMono.variable}`}
      >
        <main className={styles.main}>
          <div className="flex min-h-screen items-center justify-center bg-zinc-50 font-sans dark:bg-black">
            <main className="flex flex-col p-4 min-h-screen w-full max-w-6xl bg-white dark:bg-black">
              <h1 className="text-center text-4xl">Список продуктов</h1>

              <div className='flex justify-between px-4'>
                {/* <Link href="/products/create">
            <Button variant="outline" className='cursor-pointer'>
              <SquarePlus />
              Добавить продукт
            </Button>
          </Link>

          <ProductFilter /> */}
              </div>

              {/* {products.length */}
              <ProductList
                products={products}
                favorites={favorites}
                filter={filter}
              />
              {/* : null} */}

              {/* {pagination.total > 0 && (
          <div className='self-center mt-auto p-4'>
            {filter === "all" && <ProductPagination />}
          </div>
        )} */}
            </main>
          </div>
        </main>
      </div>
    </>
  );
}
