import { useEffect } from "react";
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import { Geist, Geist_Mono } from "next/font/google";
import { useProductStore } from "@/store/useProductStore";
import { useFetchData } from "@/hooks/useFetchData";
import { TProductsResponse} from "@/types";
import styles from "@/styles/Home.module.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export default function Home() {
  const { products, setProducts } = useProductStore();
  const { data, loading, error, fetchData } = useFetchData<TProductsResponse>();

  useEffect(() => {
    fetchData('https://jsonexamples.com/products?limit=100');
  }, []);

  useEffect(() => {
    if (data) {
      setProducts(data.products);
    }
  }, [data]);

  if (loading) return <div>Loading...</div>;
  if (error) return <div>{error}</div>;

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div
        className={`${styles.page} ${geistSans.variable} ${geistMono.variable}`}
      >
        <main className={styles.main}>
          <Image
            className={styles.logo}
            src="/products-app-next/next.svg"
            alt="Next.js logo"
            width={100}
            height={20}
            priority
          />

          <div>
            <h1>Our Products</h1>
            <div className="products-grid">
              {products.map(product => (
                <Link key={product.id} href={`/products/${product.id}`}>
                  <div className="product-card">
                    <img src={product.thumbnail} alt={product.title} />
                    <h3>{product.title}</h3>
                    <p>${product.price}</p>
                  </div>
                </Link>
              ))}
            </div>
          </div>

        </main>
      </div>
    </>
  );
}
